### PR TITLE
tab to editor and breadcrumb fixes

### LINKED ISSUE #907: Show VR Camera in breadcrumb when selected
Now we're showing everything else there, it becomes super handy, so is a bit weird that it doesn't show the VR camera when that is selected. Not sure if this is a bug, or just unimplemented due to different behaviour by the VR cam.

### LINKED ISSUE #1890: Change tab back to show the previous graph level.

### LINKED ISSUE #1891: New hotkey for "show graph of the selected object"

### LINKED ISSUE #1900: breadcrumb shows duplicated entries
screen shot 2016-09-05 at 18 23 47

related to #1890, #1891

### LINKED ISSUE #1901: breadcrumb does not refresh if parent patch node renamed by concurrent user
to reproduce:

 - open edit session in browser (B1)
 - navigate to same url in another browser (B2)
 - in B1 switch to Program, enter a subgraph node and select a node inside, e.g. Root > Rotation > If .. Else
 - in B2 switch to Program, select Rotation subgraph and rename to Rotation 1

expected in B1: Root > Rotation > If .. Else changes to Root > Rotation 1 > If .. Else
actual: breadcrumb remains the same.

### LINKED ISSUE #1902: mixpanel tracks going back to build mode 4 times
related to past changes in UIState

### PR DESCRIPTION
**Pull request by gmarinov**
- resolves #1890 - revert `tab` behaviour to toggle patch editor to its last active graph
 - resolves #1891 - `shift+tab` to open patch editor to inside of selected object
 - resolves #907 - show vr camera in breadcrumb
 - resolves #1901 - refresh breadcrumb if node renamed by concurrent user
 - resolves #1900 - breadcrumb shows duplicated entries
 - fixes #1902 - mixpanel tracking program->build many times over
 - refines breadcrumb behaviour when selecting grouped objects
 - also adds a temporary fix for error on deleting of grouped objects from world editor

### CODE REVIEW

File: browser/scripts/ui-breadcrumb.js [hunk 1]
```diff
@@ -25,6 +26,10 @@ var UIbreadcrumb = function(/* @var jQuery|null */ $existingContainer) {
 	} else {
 		this.container = null	// only produce html
 	}
+
+	Object.defineProperty(this, 'length', {
```
Comment (kschzt) [inline browser/scripts/ui-breadcrumb.js]: `length`

File: browser/scripts/ui.js [hunk 2]
```diff
@@ -502,30 +504,70 @@ VizorUI.prototype.setModeProgram = function() {
 	return true;
 };
 
-VizorUI.prototype.buildBreadcrumb = function(graph, beforeRender) {
+VizorUI.prototype.buildBreadcrumb = function(graph, selected, beforeRender) {
```
Comment (kschzt) [inline browser/scripts/ui.js]: since this doesn't actually use any UI bits, would be easy and very useful to write a unit test for this function.

File: browser/scripts/ui/uiAbstractProperties.js [hunk 3]
```diff
@@ -20,10 +20,14 @@ var UIAbstractProperties = function UIAbstractProperties(domElement) {
 	// collects exposed properties. set at render-time
 	this.adapter = null
 
+	function isGraphNode(node) {
+		return node && node.plugin && (node.plugin.parentNode === node)
```
Comment (kschzt) [inline browser/scripts/ui/uiAbstractProperties.js]: hmm, isn't this true for all nodes? did you mean to check for E2.GRAPH_NODES?

File: browser/scripts/worldEditor/worldEditor.js [hunk 4]
```diff
@@ -257,7 +263,7 @@ WorldEditor.prototype.setSelection = function(selected) {
 	if (!anySelected)
 		this.clearSelection()
 
-	E2.ui.emit('worldEditor:selectionSet')
+	this.emit('selectionSet', this.getSelectedNodes())
```
Comment (kschzt) [inline browser/scripts/worldEditor/worldEditor.js]: should this not be a Flux dispatch? so that we could be sure this doesn't ever cause any cascading changes.
the UI state store should listen to the dispatch, set the selection state, and emit the selection change.

Comment (gmarinov) [inline browser/scripts/worldEditor/worldEditor.js]: This is local. the UI store does not mediate in the work loop. Of course the worldEditor could dispatch so that the other side knows what you've selected something, but that's outside my UI scope for this task. I think worldEditor emitting on itself is now less risky to cascade than previously emitting on E2.ui, which worldEditor shouldn't know anything about.

**Comment by kschzt** [comment]
lgtm
