### PR TITLE
modal functionality and ui state fixes

### LINKED ISSUE #644: FileSelectControl cannot hide its own bootbox
had to change
	this._el.modal('hide');
to
	bootbox.hideAll();

in file-select-control.js : 399

### LINKED ISSUE #673: publish graph modal: placeholder doesn't clear upon entering text
publish dialogue

### LINKED ISSUE #695: camera buttons have no tooltips when active
is this correct behaviour, @mattatgit ?

### PR DESCRIPTION
**Pull request by gmarinov**
- unify the handling of simple forms in modal dialogs (currently used for account management), fixes #673 #688 #690 #691 #692 #704 #705 #716
 - abstract away bootbox dialogs and remove chained .init() calls that broke the elements in question, fixes #644 #732
 - tweak UI to take recent design choices into account, also fixes #695 #715

### CODE REVIEW

File: controllers/userController.js [hunk 1]
```diff
@@ -434,17 +485,30 @@ function parseErrors(errors) {
...
  		}
  		], function(err) {
- 			if (err)
+ 			if (err) {
+				res.status(500).json({ok:false, message: 'The server could not email you. Please contact us for assistance.'})
  				return next(err)
+			}
+			if (wantJSON) {
+				return res.status(200).json({
+					ok:		true,
```
Comment (kschzt) [inline controllers/userController.js]: why are you using `ok` and `success`?

Comment (kschzt) [inline controllers/userController.js]: also since these should be the same for every response, consider making these functions, something like:
```
var _ = require('lodash')
function ResponseStatusSuccess(message, options) {
    return _.extend(options || {}, { success: true, message: message})
}

```

that way it's easier to change them all at once

**Comment by kschzt** [comment]
A homework: you should find a way to "squash" those "interim" commits, by using git rebase, because they will look really bad in the commit history when we look back on master. But not necessary right now. 

Please just add functions for creating responses, then lgtm!

File: controllers/userController.js (hunk 1 above)
Comment (gmarinov) [inline controllers/userController.js]: no particular reason. I prefer to use 'success', but found too many things using 'ok'. Since this is backend, and we haven't settled on the format of responses (#596), I didn't want to touch too much.

Comment (gmarinov) [inline controllers/userController.js]: userController now typically returns
```
{ 
  success : true,
  message : 'string', 
  data: { }   // object in question
}
```
or 
```
{ 
  success: false,
  message: 'whatever went wrong',
  errors: [ { param:, msg:, value: } ],
}
```

**Comment by kschzt** [comment]
lgtm
