### PR TITLE
webvr boilerplate fixes

### LINKED ISSUE #1504: Aspect ratio is incorrect after switching between editor/vr cameras
Press V
notice aspect ratio is wrong
resize window
notice aspect ratio fixes itself

### LINKED ISSUE #1506: scrollbar on homepage:getstarted graph
seems forced to vertical dimensions of window

### PR DESCRIPTION
**Pull request by gmarinov**
resolves #1506 - wrong canvas dimensions on homepage
resolves #1504 - incorrect aspect ratio when switching between editor
cameras
fixes boilerplate regressions - canInitiateCameraMove and
getContainerDimensions now back where they were.

### CODE REVIEW

File: browser/vendor/borismus/webvr-polyfill.js [hunk 1]
```diff
@@ -5014,7 +5038,7 @@ FusionPoseSensor.prototype.onDeviceMotionChange_ = function(deviceMotion) {
   var deltaS = timestampS - this.previousTimestampS;
   if (deltaS <= Util.MIN_TIMESTEP || deltaS > Util.MAX_TIMESTEP) {
     console.warn('Invalid timestamps detected. Time step between successive ' +
-                 'gyroscope sensor samples is very small or not monotonic');
+                 'gyroscope sensor samples is very small or not monotonic ');
```
Comment (kkananen) [inline browser/vendor/borismus/webvr-polyfill.js]: do we need the extra space in the end?

**Comment by kkananen** [comment]
lgtm; however please make sure you've done this: 
1. apply the changes to our fork of boilerplate/webvr-manager (webvr-1.0-vizor branch)
2. rebuild the boilerplate (npm run build)
3. copy build/webvr-manager.js into our repo (into browser/vendor/borismus/)
4. commit both
