### PR TITLE
Resolves #1187 - set reactivated inputs' updated flag so that their v…

### LINKED ISSUE #1187: Array Revolver Switch: inactive inputs aren't updated
1. Open http://vizor.io/reiska/array-revolver-input-update-bug-reproduction
2. Switch boolean toggle on
-> number updates as expected
3. change First Number (the inactive input) to 30
4. Switch boolean toggle off
-> number incorrectly changes to 10, the previous value in input 0

### PR DESCRIPTION
**Pull request by kkananen**
…alues are properly fetched

### CODE REVIEW

File: browser/scripts/node.js [hunk 1]
```diff
@@ -411,17 +411,24 @@ Node.prototype.update_recursive = function(conns) {
...
+	// (which could change the state of activeness on other inputs)
 	for (var i = 0, len = inputs.length; i < len; ++i) {
 		var inp = inputs[i]
-
 		if (inp.dst_slot.inactive) {
-			if(inp.ui && inp.ui.flow) {
-				this._cascadeFlowOff(inp)
-				dirty = true;
+			if (inp.ui && inp.ui.flow) {
+				this._cascadeFlowOff()
```
Comment (kschzt) [inline browser/scripts/node.js]: `cascadeFlowOff()` takes one parameter!

File: browser/scripts/node.js [hunk 2]
```diff
@@ -411,17 +411,24 @@ Node.prototype.update_recursive = function(conns) {
 
 	var secondPassUpdateInputs = []
 
-	// first pass input update: update active inputs
+	// input update step 1: collect inactive inputs before any inputs haven't been updated
```
Comment (kschzt) [inline browser/scripts/node.js]: this comment is a bit unclear, do you mean "before any inputs have been"?

**Comment by kschzt** [comment]
lgtm
