### PR TITLE
Profile error handling fixes; resolves #699 and #700

### LINKED ISSUE #699: clicking Update Profile from /account crashes the (node) app
1 login
2 navigate to /account
3 click Update Profile

### PR DESCRIPTION
**Pull request by kschzt**

### CODE REVIEW

File: controllers/userController.js [hunk 1]
```diff
@@ -113,54 +115,54 @@ exports.checkUserName = function(req, res, next) {
...
- 	});
+ 	})
 
  	User.findOne({ username: req.body.username }, function(err, existingUser) {
  		if (existingUser) {
  			if (req.xhr){
  				return res.status(400).json({
-          message: 'Account with that username already exists.'
-        });
+ 					message: 'Account with that username already exists.'
```
Comment (gmarinov) [inline controllers/userController.js]: 'An account...'

File: controllers/userController.js [hunk 2]
```diff
@@ -113,54 +115,54 @@ exports.checkUserName = function(req, res, next) {
...
+ 				})
  			}
- 			return res.redirect('/signup');
+ 			return res.redirect('/signup')
  		}
  		User.findOne({ email: req.body.email }, function(err, existingUser) {
  			if (existingUser) {
  				if (req.xhr) {
- 					return res.status(400).json({ message: 'Account with that email already exists.' });
+ 					return res.status(400).json({ message: 'Account with that email already exists.' })
```
Comment (gmarinov) [inline controllers/userController.js]: 'An account...'
